apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod  
spec:
  acme:
    email: osiephriobukohwo@gmail.com  
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-secret-key 
    solvers:
    - http01:
        ingress:
          class: nginx 
