apiVersion: v1
kind: Service
metadata:
  name: jumia-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 32004