apiVersion: v1
kind: Service
metadata:
  name: jumia-backend-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-backend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  

#helm rollback release revision --namespace <namespace>